naver:
  client-id: "mh9sg9YDttBxGB05kUHA"
  client-secret: "2eV4B9VaXh"

  redirect-uri: "http://localhost:8080/api/v1/auth/naver/user"
  #  redirect-uri: "http://localhost:8080/auth/naver/callback"

jwt:
  # 운영에서는 환경변수로! 예: JWT_SECRET
  secret: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
  access-token-exp-minutes: 60