spring:
  # 데이터베이스 연결 설정
  datasource:
    # localhost:5432 뒤의 이름은 pgAdmin에서 확인한 데이터베이스 이름과 같아야 합니다.
    url: jdbc:postgresql://100.95.214.66:5432/postgres
    # 2. Username: 실제 사용자인 a085073으로 수정합니다.
    username: a085073
    # 3. Password: 실제 비밀번호인 aivle202508로 수정합니다.
    password: aivle202508
    driver-class-name: org.postgresql.Driver



app-front:
  callback-url: "https://ai0917-kt-aivle-shool-8th-bigprojec-eta.vercel.app/"   # 프론트 주소에 맞게
